/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AVHallBookingPackages;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 212704598
 */
public class BookingForm extends javax.swing.JFrame {

    BookingHandler myBHObj = BookingHandler.createBHObj();
    DatabaseHandler databaseHandler = DatabaseHandler.createDBHObj();

    public BookingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        SignOutLabel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DateLabel = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DATE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        DoneButton.setBackground(new java.awt.Color(0, 0, 0));
        DoneButton.setForeground(new java.awt.Color(255, 255, 255));
        DoneButton.setText("DONE");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        SignOutLabel.setBackground(new java.awt.Color(255, 51, 51));
        SignOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignOutLabel.setText("SIGN OUT");
        SignOutLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutLabelActionPerformed(evt);
            }
        });
        jPanel1.add(SignOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AVHallBookingPackages/realBook.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 290, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AVHallBookingPackages/BACKiCONnEW.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 60));
        jPanel1.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        Date date = DateLabel.getDate();
        if (date == null) {
            JOptionPane.showMessageDialog(this, "ENTER SUITABLE DATA");
        } else {
            boolean a;
            //a = myBHObj.createBooking(date);
            a = databaseHandler.createBooking(date);
            if (a) {
                JOptionPane.showMessageDialog(this, "BOOKING IS CONFIRMED");
                DateLabel.setCalendar(null);
            } else {
                JOptionPane.showMessageDialog(this, "DATE IS NOT AVAILABLE");
            }
        }
        DateLabel.setCalendar(null);
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void SignOutLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutLabelActionPerformed
        databaseHandler.signOut();
        dispose();
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
    }//GEN-LAST:event_SignOutLabelActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
        WelcomeForm wbf = new WelcomeForm();
        wbf.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateLabel;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton SignOutLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

}
