/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AVHallBookingPackages;

import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 212704598
 */
public class UpdateBookingForm extends javax.swing.JFrame {

    BookingHandler myBHObj = BookingHandler.createBHObj();
    DatabaseHandler databaseHandler = DatabaseHandler.createDBHObj();

    public UpdateBookingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        previousDateLabel = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        newDateLabel = new com.toedter.calendar.JDateChooser();
        newDateDoneButton = new javax.swing.JButton();
        SignOutLabel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ENTER PREVIOUS DATE:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        jPanel2.add(previousDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ENTER NEW DATE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel2.add(newDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 190, -1));

        newDateDoneButton.setBackground(new java.awt.Color(0, 0, 0));
        newDateDoneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newDateDoneButton.setForeground(new java.awt.Color(255, 255, 255));
        newDateDoneButton.setText("UPDATE BOOKING");
        newDateDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDateDoneButtonActionPerformed(evt);
            }
        });
        jPanel2.add(newDateDoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        SignOutLabel.setBackground(new java.awt.Color(255, 51, 51));
        SignOutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignOutLabel.setText("SIGN OUT");
        SignOutLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutLabelActionPerformed(evt);
            }
        });
        jPanel2.add(SignOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AVHallBookingPackages/realUpdate.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 280, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AVHallBookingPackages/BACKiCONnEW.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDateDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDateDoneButtonActionPerformed
        Date previousDate = previousDateLabel.getDate();
        Date newDate = newDateLabel.getDate();
        if (previousDate == null) {
            JOptionPane.showMessageDialog(this, "PLEASE ENTER PREVIOUS BOOKED DATE");
        }
        else if(newDate == null)
        {
            JOptionPane.showMessageDialog(this, "PLEASE ENTER NEW DATE");
        }
        else
        {
            //int updateOptions = myBHObj.updateBooking(newDate, previousDate);
            int updateOptions = databaseHandler.updateBooking(newDate, previousDate);
            if(updateOptions == 0)
            {
                JOptionPane.showMessageDialog(this, "NO BOOKING ON YOUR NAME");
                previousDateLabel.setCalendar(null);
                newDateLabel.setCalendar(null);
            }
            else if(updateOptions == 1)
            {
                JOptionPane.showMessageDialog(this, "NO BOOKING ON PREVIOUS DATE");
                previousDateLabel.setCalendar(null);
            }
            else if(updateOptions == 2)
            {
                JOptionPane.showMessageDialog(this, "NEW DATE IS NOT AVAILABLE");
                newDateLabel.setCalendar(null);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "BOOKING UPDATED");
            }
        }
    }//GEN-LAST:event_newDateDoneButtonActionPerformed

    private void SignOutLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutLabelActionPerformed
        databaseHandler.signOut();
        dispose();
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
    }//GEN-LAST:event_SignOutLabelActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "IMAGE CLICKED");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
        WelcomeForm wbf = new WelcomeForm();
        wbf.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignOutLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton newDateDoneButton;
    private com.toedter.calendar.JDateChooser newDateLabel;
    private com.toedter.calendar.JDateChooser previousDateLabel;
    // End of variables declaration//GEN-END:variables

}
